### ISSUE TITLE
Outdated setuptools version

### ISSUE THREAD

**Issue by touilleMan** [Scalingo/python-buildpack#13]
https://github.com/Scalingo/python-buildpack/blob/1e3eda584089c767174033b832b2bfa191a06ee5/bin/steps/python#L163

setuptools 39.0.1 is two years old, and doesn't support the new manylinux2014 wheels format.

I think it would be better to do a `pip install -U pip setuptools` here (and maybe providing environ variable to allow user to pin pip/setuptools to a specific version if needed)

**Comment by EtienneM** [comment]
Closed by #15

**Comment by touilleMan** [comment]
thanks ;-)
