### ISSUE TITLE
Update buildpack to align on heroku for more recent Pip version

### ISSUE THREAD

**Issue by cyrille-sg** [Scalingo/python-buildpack#19]
Some deps (like said here https://github.com/heroku/heroku-buildpack-python/pull/1169) are not compatible with current Pip version.

Change were made to solve this: https://devcenter.heroku.com/changelog-items/2029

**Comment by lazybird** [comment]
Hello,
Thanks for you work on this buildpack.

Do you have an idea when this is issue is going to be addressed ?

This is a blocking issue, I think : some pip packages fail installing without this update.

Thanks

**Comment by EtienneM** [comment]
Duplicate of #14
