### ISSUE TITLE
Handle rust dependency by some libs

### ISSUE THREAD

**Issue by ksol** [Scalingo/python-buildpack#20]
Some libs are starting to depend on rust : https://github.com/pyca/cryptography/issues/5771

this can cause issues at build time, so this should probably handled by the buildpack. It looks like upstream has been updated to include this : https://github.com/heroku/heroku-buildpack-python/pull/1169

**Comment by Jean-Serge** [comment]
It seems that it is handled by the buildpack but only with the latest pip version.

My issue was that I'm using pipenv and [those lines](https://github.com/Scalingo/python-buildpack/blob/master/bin/compile#L83-L86) prevent pip to update.

A fork where those lines are removed currently work for my app.

**Comment by curzolapierre** [comment]
Should be fixed since the buildpack as been sync with upstream
